// Writes src/generated.js: the GitHub repository (from package.json) and the size and SHA-256 of every
// anatomy file in assets/, so the plugin can fetch them from the matching release and check them.
import { readFileSync, readdirSync, writeFileSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url)));
const repo = String((pkg.repository && pkg.repository.url) || pkg.repository || '').replace(/^.*github\.com[/:]/, '').replace(/\.git$/, '');
// the anatomy files live in their own release (they change rarely), so plugin releases carry only the three files Obsidian installs
const release = String((pkg.config && pkg.config.anatomyRelease) || '');
const dir = new URL('../assets/', import.meta.url);
const assets = {};
for (const f of readdirSync(dir).filter(n => n.endsWith('.bin.gz')).sort()) {
  const buf = readFileSync(new URL(f, dir));
  assets[f] = { size: statSync(new URL(f, dir)).size, sha256: createHash('sha256').update(buf).digest('hex') };
}
writeFileSync(new URL('../src/generated.js', import.meta.url),
  '// Generated by tools/prepare.mjs. Do not edit.\n' +
  `export const REPO = ${JSON.stringify(repo)};\n` +
  `export const ASSET_RELEASE = ${JSON.stringify(release)};\n` +
  `export const ASSETS = ${JSON.stringify(assets, null, 2)};\n`);
console.log('generated.js:', repo || '(no repository in package.json)', release || '(no anatomy release)', Object.keys(assets).length, 'assets');
